# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import Qt

import time
import os
from conection.conexion import establecer_conexion
from voices.voices import talk
from camara.face_trainer import trainer
from camara.face_capture import capture_video
from camara.face_capture import run as runcapture
from security.protect import (hash_password, 
                              verificar_len_password, 
                              verificar_capital_password, 
                              verificar_digit_password, 
                              verificar_illegal_character_password, 
                              verificar_space_password, 
                              verificar_exist_password_regist,
                              validar_telefono_movil,
                              validar_correo_electronico
                              ) 


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(249, 358)
        self.centralwidget = QtWidgets.QWidget(Register)
        self.centralwidget.setObjectName("centralwidget")
        self.name_label_register = QtWidgets.QLabel(self.centralwidget)
        self.name_label_register.setGeometry(QtCore.QRect(20, 30, 61, 19))
        self.name_label_register.setStyleSheet("color: rgb(255, 255, 255);")
        self.name_label_register.setObjectName("name_label_register")
        self.name_entry_register = QtWidgets.QLineEdit(self.centralwidget)
        self.name_entry_register.setGeometry(QtCore.QRect(110, 30, 113, 25))
        self.name_entry_register.setObjectName("name_entry_register")
        self.last_name_entry_register = QtWidgets.QLineEdit(self.centralwidget)
        self.last_name_entry_register.setGeometry(QtCore.QRect(110, 70, 113, 25))
        self.last_name_entry_register.setObjectName("last_name_entry_register")
        self.email_entry_register = QtWidgets.QLineEdit(self.centralwidget)
        self.email_entry_register.setGeometry(QtCore.QRect(110, 110, 113, 25))
        self.email_entry_register.setObjectName("email_entry_register")
        self.phone_entry_register = QtWidgets.QLineEdit(self.centralwidget)
        self.phone_entry_register.setGeometry(QtCore.QRect(110, 150, 113, 25))
        self.phone_entry_register.setPlaceholderText("Ejm: +34763532456")
        self.phone_entry_register.setObjectName("phone_entry_register")
        self.user_entry_register = QtWidgets.QLineEdit(self.centralwidget)
        self.user_entry_register.setGeometry(QtCore.QRect(110, 190, 113, 25))
        self.user_entry_register.setObjectName("user_entry_register")
        self.password_entry_register = QtWidgets.QLineEdit(self.centralwidget)
        self.password_entry_register.setGeometry(QtCore.QRect(110, 230, 113, 25))
        self.password_entry_register.setObjectName("password_entry_register")
        self.last_name_label_register = QtWidgets.QLabel(self.centralwidget)
        self.last_name_label_register.setGeometry(QtCore.QRect(20, 70, 91, 19))
        self.last_name_label_register.setStyleSheet("color: rgb(255, 255, 255);")
        self.last_name_label_register.setObjectName("last_name_label_register")
        self.email_label_register = QtWidgets.QLabel(self.centralwidget)
        self.email_label_register.setGeometry(QtCore.QRect(20, 110, 61, 19))
        self.email_label_register.setStyleSheet("color: rgb(255, 255, 255);")
        self.email_label_register.setObjectName("email_label_register")
        self.phone_label_register = QtWidgets.QLabel(self.centralwidget)
        self.phone_label_register.setGeometry(QtCore.QRect(20, 150, 61, 19))
        self.phone_label_register.setStyleSheet("color: rgb(255, 255, 255);")
        self.phone_label_register.setObjectName("phone_label_register")
        self.user_label_register = QtWidgets.QLabel(self.centralwidget)
        self.user_label_register.setGeometry(QtCore.QRect(20, 190, 51, 19))
        self.user_label_register.setStyleSheet("color: rgb(255, 255, 255);")
        self.user_label_register.setObjectName("user_label_register")
        self.password_label_register = QtWidgets.QLabel(self.centralwidget)
        self.password_label_register.setGeometry(QtCore.QRect(20, 230, 81, 19))
        self.password_label_register.setStyleSheet("color: rgb(255, 255, 255);")
        self.password_label_register.setObjectName("password_label_register")
        self.pushButton_register = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_register.setGeometry(QtCore.QRect(70, 290, 91, 31))
        self.pushButton_register.setStyleSheet("QPushButton {\n"
"    background-color: rgb(23, 231, 183);\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(23, 231, 183, 150);\n"
"}\n"
"")
        self.pushButton_register.setObjectName("pushButton_register")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 251, 361))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x3:1, y2:2, stop:0 rgba(10, 38, 31, 255), stop:1 rgba(1, 229, 161, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.name_label_register.raise_()
        self.name_entry_register.raise_()
        self.last_name_entry_register.raise_()
        self.email_entry_register.raise_()
        self.phone_entry_register.raise_()
        self.user_entry_register.raise_()
        self.password_entry_register.raise_()
        self.last_name_label_register.raise_()
        self.email_label_register.raise_()
        self.phone_label_register.raise_()
        self.user_label_register.raise_()
        self.password_label_register.raise_()
        self.pushButton_register.raise_()
        Register.setCentralWidget(self.centralwidget)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)
        Register.setWindowFlags(QtCore.Qt.WindowTitleHint | QtCore.Qt.WindowCloseButtonHint)


    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "MainWindow"))
        self.name_label_register.setText(_translate("Register", "Name :"))
        self.last_name_label_register.setText(_translate("Register", "Last Name :"))
        self.email_label_register.setText(_translate("Register", "Email :"))
        self.phone_label_register.setText(_translate("Register", "Phone :"))
        self.user_label_register.setText(_translate("Register", "User :"))
        self.password_label_register.setText(_translate("Register", "Password :"))
        self.pushButton_register.setText(_translate("Register", "Register"))
        self.pushButton_register.clicked.connect(self.registers)

    def registers(self):
        self.u = QtWidgets.QMainWindow()
        name = self.name_entry_register.text()
        last_name = self.last_name_entry_register.text()
        email = self.email_entry_register.text()
        telf = self.phone_entry_register.text()
        user_name = self.user_entry_register.text()
        password = self.password_entry_register.text()
        

        hashed_password, salt = hash_password(password)
        if verificar_len_password(password) and \
           verificar_space_password(password) and \
           verificar_capital_password(password) and \
           verificar_digit_password(password) and \
           verificar_exist_password_regist(user_name, password, name, last_name) and \
           validar_telefono_movil(telf) and \
           validar_correo_electronico(email) and \
           verificar_illegal_character_password(password):
            pass
        else:
            talk("Contraseña no válida. Acceso denegado.")
            return
        conn = establecer_conexion()
        try:
            # Insertar datos en la base de datos
            cursor = conn.cursor()
            cursor.execute('INSERT INTO usuarios (Nombre, Apellido, Email, Telefono, User, hashed_password, salt) VALUES (?, ?, ?, ?, ?, ?, ?)', (name, last_name, email, telf, user_name, hashed_password, salt))
            conn.commit()
            QMessageBox.information(self.u, "Éxito", "Usuario creado con éxito")
            
            # Llama a la función para capturar el video de la reconocimiento
            capture_video()
            # cerrar la ventana despues de terminar el reconocimiento
            self.u.close()
            # Llama a la función para capturar el rostro del video para el reconocimiento del usuario nuevo
            runcapture(name)
            # Espera un tiempo antes de eliminar el video temporal
            time.sleep(1)
            # Ruta del archivo de video con el número de seguimiento
            video_filename = f'camara\\video_usuario_1.avi'
            # Elimina el video temporal
            os.remove(video_filename)
            # Entrenando el modelo de reconocimiento
            trainer()
            talk("Ya puede iniciar seción")
            
            # Limpiar campos de entrada
            self.name_entry_register.clear()
            self.last_name_entry_register.clear()
            self.email_entry_register.clear()
            self.phone_entry_register.clear()
            self.user_entry_register.clear()
            self.password_entry_register.clear()

        except Exception as e:
            QMessageBox.critical(self.u, "Error", f"Error al crear usuario: {e}")

        finally:
            conn.close()